[2025-01-09T16:58:15.091-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-09T16:58:15.106-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe scheduled__2025-01-08T20:00:00+00:00 [queued]>
[2025-01-09T16:58:15.119-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe scheduled__2025-01-08T20:00:00+00:00 [queued]>
[2025-01-09T16:58:15.120-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-09T16:58:15.140-0800] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): clean_up_sql_exe> on 2025-01-08 20:00:00+00:00
[2025-01-09T16:58:15.143-0800] {standard_task_runner.py:72} INFO - Started process 16887 to run task
[2025-01-09T16:58:15.152-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'clean_up_sql_exe', 'scheduled__2025-01-08T20:00:00+00:00', '--job-id', '1755', '--raw', '--subdir', 'DAGS_FOLDER/CovidE2EPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmpn9o7_yk8']
[2025-01-09T16:58:15.155-0800] {standard_task_runner.py:105} INFO - Job 1755: Subtask clean_up_sql_exe
[2025-01-09T16:58:15.219-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.clean_up_sql_exe scheduled__2025-01-08T20:00:00+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-09T16:58:15.344-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='clean_up_sql_exe' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T20:00:00+00:00'
[2025-01-09T16:58:15.345-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-09T16:58:15.363-0800] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T
[2025-01-09T16:58:15.365-0800] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'snow stage remove @CovidE2EPipeDatabase.raw_data.raw_data_stage/load_staged_data_2025-01-09.sql;                   rm /Users/matthewmac/airflow/helper_scripts/load_staged_data_2025-01-09.sql']
[2025-01-09T16:58:15.376-0800] {subprocess.py:99} INFO - Output:
[2025-01-09T16:58:19.329-0800] {subprocess.py:106} INFO - ╭─ Error ──────────╮
[2025-01-09T16:58:19.330-0800] {subprocess.py:106} INFO - │ Specified name   │
[2025-01-09T16:58:19.332-0800] {subprocess.py:106} INFO - │ '@CovidE2EPipeDa │
[2025-01-09T16:58:19.333-0800] {subprocess.py:106} INFO - │ tabase.raw_data. │
[2025-01-09T16:58:19.335-0800] {subprocess.py:106} INFO - │ raw_data_stage/l │
[2025-01-09T16:58:19.336-0800] {subprocess.py:106} INFO - │ oad_staged_data_ │
[2025-01-09T16:58:19.337-0800] {subprocess.py:106} INFO - │ 2025-01-09.sql'  │
[2025-01-09T16:58:19.337-0800] {subprocess.py:106} INFO - │ is not valid     │
[2025-01-09T16:58:19.338-0800] {subprocess.py:106} INFO - │ name.            │
[2025-01-09T16:58:19.340-0800] {subprocess.py:106} INFO - ╰──────────────────╯
[2025-01-09T16:58:19.855-0800] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-09T16:58:19.891-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-09T16:58:19.892-0800] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=CovidE2EPipeDag, task_id=clean_up_sql_exe, run_id=scheduled__2025-01-08T20:00:00+00:00, execution_date=20250108T200000, start_date=20250110T005815, end_date=20250110T005819
[2025-01-09T16:58:19.925-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-09T16:58:19.967-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-09T16:58:19.968-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
