[2025-01-04T11:17:22.363-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-04T11:17:22.376-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe scheduled__2025-01-01T00:59:00+00:00 [queued]>
[2025-01-04T11:17:22.386-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe scheduled__2025-01-01T00:59:00+00:00 [queued]>
[2025-01-04T11:17:22.387-0800] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-04T11:17:22.448-0800] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): clean_up_sql_exe> on 2025-01-01 00:59:00+00:00
[2025-01-04T11:17:22.452-0800] {standard_task_runner.py:72} INFO - Started process 77170 to run task
[2025-01-04T11:17:22.460-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'clean_up_sql_exe', 'scheduled__2025-01-01T00:59:00+00:00', '--job-id', '864', '--raw', '--subdir', 'DAGS_FOLDER/CovidE2EPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmpglwvgklh']
[2025-01-04T11:17:22.464-0800] {standard_task_runner.py:105} INFO - Job 864: Subtask clean_up_sql_exe
[2025-01-04T11:17:22.519-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.clean_up_sql_exe scheduled__2025-01-01T00:59:00+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-04T11:17:22.609-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='clean_up_sql_exe' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:59:00+00:00'
[2025-01-04T11:17:22.611-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-04T11:17:22.633-0800] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T
[2025-01-04T11:17:22.635-0800] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'snow stage remove @raw_data_stage/load_staged_data_2025-01-04.sql;                   rm /Users/matthewmac/airflow/helper_scripts/load_staged_data_2025-01-04.sql']
[2025-01-04T11:17:22.642-0800] {subprocess.py:99} INFO - Output:
[2025-01-04T11:17:25.942-0800] {subprocess.py:106} INFO - ╭─ Error ─────────────────────────────────────────────────────╮
[2025-01-04T11:17:25.943-0800] {subprocess.py:106} INFO - │ Specified name                                              │
[2025-01-04T11:17:25.944-0800] {subprocess.py:106} INFO - │ '@raw_data_stage/load_staged_data_2025-01-04.sql' is not    │
[2025-01-04T11:17:25.944-0800] {subprocess.py:106} INFO - │ valid name.                                                 │
[2025-01-04T11:17:25.945-0800] {subprocess.py:106} INFO - ╰─────────────────────────────────────────────────────────────╯
[2025-01-04T11:17:26.244-0800] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-04T11:17:26.271-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-04T11:17:26.273-0800] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=CovidE2EPipeDag, task_id=clean_up_sql_exe, run_id=scheduled__2025-01-01T00:59:00+00:00, execution_date=20250101T005900, start_date=20250104T191722, end_date=20250104T191726
[2025-01-04T11:17:26.297-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-04T11:17:26.322-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-04T11:17:26.323-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
