[2025-01-08T19:40:57.431-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T19:40:57.447-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-09T03:38:16.240891+00:00 [queued]>
[2025-01-08T19:40:57.458-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-09T03:38:16.240891+00:00 [queued]>
[2025-01-08T19:40:57.458-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-08T19:40:57.474-0800] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): clean_up_sql_exe> on 2025-01-09 03:38:16.240891+00:00
[2025-01-08T19:40:57.479-0800] {standard_task_runner.py:72} INFO - Started process 10224 to run task
[2025-01-08T19:40:57.489-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'clean_up_sql_exe', 'manual__2025-01-09T03:38:16.240891+00:00', '--job-id', '1694', '--raw', '--subdir', 'DAGS_FOLDER/CovidE2EPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmpzhl8gkc2']
[2025-01-08T19:40:57.492-0800] {standard_task_runner.py:105} INFO - Job 1694: Subtask clean_up_sql_exe
[2025-01-08T19:40:57.548-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-09T03:38:16.240891+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-08T19:40:57.654-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='clean_up_sql_exe' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T03:38:16.240891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-09T03:38:16.240891+00:00'
[2025-01-08T19:40:57.656-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T19:40:57.673-0800] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T
[2025-01-08T19:40:57.674-0800] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'snow stage remove @CovidE2EPipeDatabase.raw_data.raw_data_stage/load_staged_data_2025-01-08.sql;                   rm /Users/matthewmac/airflow/helper_scripts/load_staged_data_2025-01-08.sql']
[2025-01-08T19:40:57.683-0800] {subprocess.py:99} INFO - Output:
[2025-01-08T19:41:00.982-0800] {subprocess.py:106} INFO - ╭─ Error ───────────────────────────────────────────╮
[2025-01-08T19:41:00.983-0800] {subprocess.py:106} INFO - │ Specified name                                    │
[2025-01-08T19:41:00.984-0800] {subprocess.py:106} INFO - │ '@CovidE2EPipeDatabase.raw_data.raw_data_stage/lo │
[2025-01-08T19:41:00.986-0800] {subprocess.py:106} INFO - │ ad_staged_data_2025-01-08.sql' is not valid name. │
[2025-01-08T19:41:00.986-0800] {subprocess.py:106} INFO - ╰───────────────────────────────────────────────────╯
[2025-01-08T19:41:01.281-0800] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-08T19:41:01.322-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T19:41:01.325-0800] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=CovidE2EPipeDag, task_id=clean_up_sql_exe, run_id=manual__2025-01-09T03:38:16.240891+00:00, execution_date=20250109T033816, start_date=20250109T034057, end_date=20250109T034101
[2025-01-08T19:41:01.353-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-08T19:41:01.406-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T19:41:01.408-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
